### ISSUE TITLE
Archive this repo?

### ISSUE THREAD

**Issue by Morl99** [dbsystel/excote#6]
I am no longer using this project, and my guess is, that no one at our organisation is either.
@Alex-H-stud  @steffakasid are you ok with archiving this repo?
@cornelius @mxmehl FYI

**Comment by cornelius** [comment]
Thanks for being transparent about the state of the project and gracefully phasing it out. Archiving (maybe with a hint in the READEM) sounds like a good solution, if the project is not actively used anymore. If there is interest by somebody to revive it, we can still do that at any time.

**Comment by mxmehl** [comment]
I will just archive it.
